before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly libzmq3-dev
script:
  - make all test
  - ./bin/test
  - ./bin/example
