[package]
name = "elasticsearch"
version = "0.2.0"
authors = [ "erick.tryzelaar@gmail.com" ]

[[lib]]
name = "elasticsearch"
path = "src/elasticsearch/lib.rs"

[[example]]
name = "example"
path = "examples/main.rs"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq"
